PKG_NAME = libdvbcsa
PKG_VERS = 1.1.0
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://download.videolan.org/pub/videolan/libdvbcsa/1.1.0
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = http://download.videolan.org/pub/videolan/libdvbcsa/1.1.0/
COMMENT  = libdvbcsa 1.1.0
LICENSE  =

CONFIGURE_ARGS =   cross_compiling=yes  --prefix=$(INSTALL_PREFIX) 

include ../../mk/spksrc.cross-cc.mk

